### ISSUE TITLE
Need MYSQL_OPT_RECONNECT

### ISSUE THREAD

**Issue by renkun-ken** [r-dbi/dbi3#32]
Typically, I can specify several mysql options before connecting using MariaDB C Connector introduced at <https://mariadb.com/kb/en/library/mysql_optionsv/> like the following:

```c
MYSQL *mysql = mysql_init(nullptr);
mysql_options(mysql, MYSQL_OPT_RECONNECT, &config.reconnect);
mysql_options(mysql, MYSQL_OPT_LOCAL_INFILE, 0);
mysql_options(mysql, MYSQL_INIT_COMMAND, "SET autocommit=0");
```

However, I don't find a way to specify `MYSQL_OPT_RECONNECT` in RMariaDB. I'm wondering if there any possibility to support this?

**Comment by krlmlr** [comment]
Reconnection should be defined by the interface, with proper events and conditions when it's safe to reconnect (e.g. only outside of transactions).

**Comment by renkun-ken** [comment]
Any updates on this?

I think I just need a way to turn on this option when creating a connection, just like specifying some other options such as `MYSQL_OPT_READ_TIMEOUT` and `MYSQL_OPT_WRITE_TIMEOUT`. Its behavior should be defined in [https://mariadb.com/kb/en/mysql_optionsv/] and I acutally don't expect RMariaDB to do anything else.

**Comment by renkun-ken** [comment]
What if we just add `reconnect` to <https://github.com/r-dbi/RMariaDB/blob/main/src/DbConnection.cpp#L30> so that user could simply opt-in `MYSQL_OPT_RECONNECT`?

**Comment by krlmlr** [comment]
We could do it for RMariaDB if you need it, clearly marking it as experimental and somewhat dangerous. Would you like to submit a PR?

**Comment by renkun-ken** [comment]
Yes, I'll submit a PR shortly.
